{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "34f91982-15b3-49aa-a951-abda9bba8c59",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: opencv-python in c:\\users\\kiit\\anaconda3\\lib\\site-packages (4.13.0.92)\n",
      "Requirement already satisfied: numpy>=2 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from opencv-python) (2.3.5)\n"
     ]
    }
   ],
   "source": [
    "!pip install opencv-python"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "c01d3505-3d06-4f12-b570-d06c24bf19bd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: ipywidgets in c:\\users\\kiit\\anaconda3\\lib\\site-packages (8.1.7)\n",
      "Requirement already satisfied: comm>=0.1.3 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from ipywidgets) (0.2.3)\n",
      "Requirement already satisfied: ipython>=6.1.0 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from ipywidgets) (9.7.0)\n",
      "Requirement already satisfied: traitlets>=4.3.1 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from ipywidgets) (5.14.3)\n",
      "Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from ipywidgets) (4.0.14)\n",
      "Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from ipywidgets) (3.0.15)\n",
      "Requirement already satisfied: colorama>=0.4.4 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)\n",
      "Requirement already satisfied: decorator>=4.3.2 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)\n",
      "Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)\n",
      "Requirement already satisfied: jedi>=0.18.1 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)\n",
      "Requirement already satisfied: matplotlib-inline>=0.1.5 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)\n",
      "Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)\n",
      "Requirement already satisfied: pygments>=2.11.0 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)\n",
      "Requirement already satisfied: stack_data>=0.6.0 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)\n",
      "Requirement already satisfied: wcwidth in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from jedi>=0.18.1->ipython>=6.1.0->ipywidgets) (0.8.5)\n",
      "Requirement already satisfied: executing>=1.2.0 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)\n",
      "Requirement already satisfied: asttokens>=2.1.0 in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.0)\n",
      "Requirement already satisfied: pure_eval in c:\\users\\kiit\\anaconda3\\lib\\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)\n"
     ]
    }
   ],
   "source": [
    "!pip install ipywidgets"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "21362751-4460-46a5-9f05-e761b653dba7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4.13.0\n"
     ]
    }
   ],
   "source": [
    "import cv2\n",
    "print(cv2.__version__)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "7720bbf6-d3a1-4c5b-b8e8-8b44048b0227",
   "metadata": {},
   "outputs": [],
   "source": [
    "run_thread = False\n",
    "cv2.destroyAllWindows()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "15d1c846-8932-473b-8ab5-0ae347944099",
   "metadata": {},
   "source": [
    "IMPORTS :"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "89504d70-7945-49bd-ae34-22ad06ede936",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "import threading\n",
    "import time\n",
    "from datetime import datetime\n",
    "\n",
    "import ipywidgets as widgets\n",
    "from IPython.display import display"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "28de284a-8050-4ead-82e0-5d3074fb30c9",
   "metadata": {},
   "source": [
    "GLOBAL VARIABLES :"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "b3b845b2-f9bb-460e-8735-cb6403e8949e",
   "metadata": {},
   "outputs": [],
   "source": [
    "run_thread = False\n",
    "\n",
    "video_thread = None\n",
    "fps_thread = None\n",
    "\n",
    "frame_counter = 0\n",
    "fps = 0\n",
    "\n",
    "latest_frame = None\n",
    "\n",
    "camera_index = 0\n",
    "\n",
    "capture_width = 1280\n",
    "capture_height = 720"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a2052cac-9984-4b9a-942a-f13c48bf080e",
   "metadata": {},
   "source": [
    "KERNEL LIBRARY :"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "2385bd77-bee2-4795-ae3d-a3d9e586cf88",
   "metadata": {},
   "outputs": [],
   "source": [
    "sharpen_kernel = np.array(\n",
    "[\n",
    "[0,-1,0],\n",
    "[-1,5,-1],\n",
    "[0,-1,0]\n",
    "],dtype=np.float32)\n",
    "\n",
    "\n",
    "box_kernel = np.ones((9,9),dtype=np.float32)/81\n",
    "\n",
    "\n",
    "gaussian_kernel = np.array(\n",
    "[\n",
    "[1,2,1],\n",
    "[2,4,2],\n",
    "[1,2,1]\n",
    "],dtype=np.float32)/16\n",
    "\n",
    "\n",
    "emboss_kernel = np.array(\n",
    "[\n",
    "[-2,-1,0],\n",
    "[-1,1,1],\n",
    "[0,1,2]\n",
    "],dtype=np.float32)\n",
    "\n",
    "\n",
    "dilate_kernel = np.ones((3,3),np.uint8)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b4c7fc6c-d4e7-44a2-a3cc-b7fbf2a49d8a",
   "metadata": {},
   "source": [
    "GUI WIDGETS : "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "97a61147-aa9a-449c-b27e-0937e46fe6de",
   "metadata": {},
   "outputs": [],
   "source": [
    "start_button = widgets.Button(\n",
    "    description='Start',\n",
    "    button_style='success'\n",
    ")\n",
    "\n",
    "stop_button = widgets.Button(\n",
    "    description='Stop',\n",
    "    button_style='danger'\n",
    ")\n",
    "\n",
    "capture_button = widgets.Button(\n",
    "    description='Capture Frame',\n",
    "    button_style='warning'\n",
    ")\n",
    "\n",
    "mode_dropdown = widgets.Dropdown(\n",
    "\n",
    "    options=[\n",
    "\n",
    "        \"Pass Through\",\n",
    "        \"Sharpen\",\n",
    "        \"Box Blur\",\n",
    "        \"Gaussian Blur\",\n",
    "        \"Emboss\",\n",
    "        \"Filter2D + Dilate\",\n",
    "        \"Sobel Edge\",\n",
    "        \"Canny Edge\"\n",
    "\n",
    "    ],\n",
    "\n",
    "    value=\"Pass Through\",\n",
    "\n",
    "    description=\"Mode:\"\n",
    ")\n",
    "\n",
    "grayscale_checkbox = widgets.Checkbox(\n",
    "\n",
    "    value=False,\n",
    "\n",
    "    description='Grayscale'\n",
    "\n",
    ")\n",
    "# BRIGHTNESS SLIDER\n",
    "brightness_slider = widgets.IntSlider(\n",
    "\n",
    "value=0,\n",
    "\n",
    "min=-100,\n",
    "\n",
    "max=100,\n",
    "\n",
    "step=1,\n",
    "\n",
    "description='Brightness'\n",
    "\n",
    ")\n",
    "# CONTRAST SLIDER\n",
    "contrast_slider = widgets.FloatSlider(\n",
    "\n",
    "value=1.0,\n",
    "\n",
    "min=0.2,\n",
    "\n",
    "max=3.0,\n",
    "\n",
    "step=0.1,\n",
    "\n",
    "description='Contrast'\n",
    "\n",
    ")\n",
    "# CANNY LOW THRESHOLD\n",
    "canny_low_slider = widgets.IntSlider(\n",
    "\n",
    "value=50,\n",
    "\n",
    "min=0,\n",
    "\n",
    "max=255,\n",
    "\n",
    "step=1,\n",
    "\n",
    "description='Canny Low'\n",
    "\n",
    ")\n",
    "# CANNY HIGH THRESHOLD\n",
    "canny_high_slider = widgets.IntSlider(\n",
    "\n",
    "value=150,\n",
    "\n",
    "min=0,\n",
    "\n",
    "max=255,\n",
    "\n",
    "step=1,\n",
    "\n",
    "description='Canny High'\n",
    "\n",
    ")\n",
    "# LABELS\n",
    "status_label = widgets.Label(\n",
    "value=\"Stopped\"\n",
    ")\n",
    "\n",
    "fps_label = widgets.Label(\n",
    "value=\"FPS : 0\"\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "65cc89cd-134b-4d54-9649-6a4e7dc16043",
   "metadata": {},
   "source": [
    "IMAGE FRAME CAPTURE FUNCTION :"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "65c804eb-fa05-4fac-b9cd-bde4bd2957f8",
   "metadata": {},
   "outputs": [],
   "source": [
    "def capture_image(b):\n",
    "\n",
    "    global latest_frame\n",
    "\n",
    "    if latest_frame is None:\n",
    "\n",
    "        print(\"No frame available\")\n",
    "        return\n",
    "\n",
    "    filename = datetime.now().strftime(\n",
    "        \"capture_%Y%m%d_%H%M%S.png\"\n",
    "    )\n",
    "\n",
    "    cv2.imwrite(filename, latest_frame)\n",
    "\n",
    "    print(\"Saved :\", filename)\n",
    "\n",
    "\n",
    "capture_button.on_click(capture_image)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d571f09a-8672-4071-9229-5ca48f1e4979",
   "metadata": {},
   "source": [
    "FPS THREAD :"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "ff029ec8-aae6-482b-baea-0cc565276128",
   "metadata": {},
   "outputs": [],
   "source": [
    "def fps_reporter():\n",
    "\n",
    "    global frame_counter\n",
    "    global fps\n",
    "    global run_thread\n",
    "\n",
    "    prev_time = time.time()\n",
    "\n",
    "    while run_thread:\n",
    "\n",
    "        time.sleep(1)\n",
    "\n",
    "        curr_time = time.time()\n",
    "\n",
    "        elapsed = curr_time - prev_time\n",
    "\n",
    "        if elapsed > 0:\n",
    "            fps = frame_counter / elapsed\n",
    "        else:\n",
    "            fps = 0\n",
    "\n",
    "        frame_counter = 0\n",
    "\n",
    "        prev_time = curr_time\n",
    "\n",
    "        fps_label.value = f\"FPS : {fps:.2f}\""
   ]
  },
  {
   "cell_type": "markdown",
   "id": "153be45e-0260-4b01-83c7-954129cce0ad",
   "metadata": {},
   "source": [
    "VIDEO PROCESSING THREAD :"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "c267c3ae-c640-49ce-9af4-10d7b145efab",
   "metadata": {},
   "outputs": [],
   "source": [
    "def process_video_stream():\n",
    "\n",
    "    global run_thread\n",
    "    global frame_counter\n",
    "    global latest_frame\n",
    "    global fps\n",
    "\n",
    "    cap = cv2.VideoCapture(camera_index)\n",
    "\n",
    "    cap.set(cv2.CAP_PROP_FRAME_WIDTH, capture_width)\n",
    "    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, capture_height)\n",
    "\n",
    "    if not cap.isOpened():\n",
    "\n",
    "        status_label.value = \"Camera Error\"\n",
    "\n",
    "        run_thread = False\n",
    "\n",
    "        return\n",
    "\n",
    "    while run_thread:\n",
    "\n",
    "        ret, frame = cap.read()\n",
    "\n",
    "        if not ret:\n",
    "            break\n",
    "\n",
    "        ###################################################\n",
    "        # Brightness + Contrast\n",
    "        ###################################################\n",
    "\n",
    "        frame_adj = cv2.convertScaleAbs(\n",
    "\n",
    "            frame,\n",
    "\n",
    "            alpha=contrast_slider.value,\n",
    "\n",
    "            beta=brightness_slider.value\n",
    "\n",
    "        )\n",
    "\n",
    "        ###################################################\n",
    "        # Mode\n",
    "        ###################################################\n",
    "\n",
    "        mode = mode_dropdown.value\n",
    "\n",
    "        ###################################################\n",
    "        # Processing Modes\n",
    "        ###################################################\n",
    "\n",
    "        if mode == \"Pass Through\":\n",
    "\n",
    "            processed = frame_adj.copy()\n",
    "\n",
    "        elif mode == \"Sharpen\":\n",
    "\n",
    "            processed = cv2.filter2D(\n",
    "\n",
    "                frame_adj,\n",
    "\n",
    "                -1,\n",
    "\n",
    "                sharpen_kernel\n",
    "\n",
    "            )\n",
    "\n",
    "        elif mode == \"Box Blur\":\n",
    "\n",
    "            processed = cv2.filter2D(\n",
    "\n",
    "                frame_adj,\n",
    "\n",
    "                -1,\n",
    "\n",
    "                box_kernel\n",
    "\n",
    "            )\n",
    "\n",
    "        elif mode == \"Gaussian Blur\":\n",
    "\n",
    "            processed = cv2.filter2D(\n",
    "\n",
    "                frame_adj,\n",
    "\n",
    "                -1,\n",
    "\n",
    "                gaussian_kernel\n",
    "\n",
    "            )\n",
    "\n",
    "        elif mode == \"Emboss\":\n",
    "\n",
    "            processed = cv2.filter2D(\n",
    "\n",
    "                frame_adj,\n",
    "\n",
    "                -1,\n",
    "\n",
    "                emboss_kernel\n",
    "\n",
    "            )\n",
    "\n",
    "        elif mode == \"Filter2D + Dilate\":\n",
    "\n",
    "            temp = cv2.filter2D(\n",
    "\n",
    "                frame_adj,\n",
    "\n",
    "                -1,\n",
    "\n",
    "                sharpen_kernel\n",
    "\n",
    "            )\n",
    "\n",
    "            processed = cv2.dilate(\n",
    "\n",
    "                temp,\n",
    "\n",
    "                dilate_kernel,\n",
    "\n",
    "                iterations=1\n",
    "\n",
    "            )\n",
    "\n",
    "        elif mode == \"Sobel Edge\":\n",
    "\n",
    "            gray = cv2.cvtColor(\n",
    "\n",
    "                frame_adj,\n",
    "\n",
    "                cv2.COLOR_BGR2GRAY\n",
    "\n",
    "            )\n",
    "\n",
    "            sx = cv2.Sobel(\n",
    "\n",
    "                gray,\n",
    "\n",
    "                cv2.CV_64F,\n",
    "\n",
    "                1,\n",
    "\n",
    "                0,\n",
    "\n",
    "                ksize=3\n",
    "\n",
    "            )\n",
    "\n",
    "            sy = cv2.Sobel(\n",
    "\n",
    "                gray,\n",
    "\n",
    "                cv2.CV_64F,\n",
    "\n",
    "                0,\n",
    "\n",
    "                1,\n",
    "\n",
    "                ksize=3\n",
    "\n",
    "            )\n",
    "\n",
    "            sx = cv2.convertScaleAbs(sx)\n",
    "\n",
    "            sy = cv2.convertScaleAbs(sy)\n",
    "\n",
    "            processed = cv2.addWeighted(\n",
    "\n",
    "                sx,\n",
    "\n",
    "                0.5,\n",
    "\n",
    "                sy,\n",
    "\n",
    "                0.5,\n",
    "\n",
    "                0\n",
    "\n",
    "            )\n",
    "\n",
    "        elif mode == \"Canny Edge\":\n",
    "\n",
    "            gray = cv2.cvtColor(\n",
    "\n",
    "                frame_adj,\n",
    "\n",
    "                cv2.COLOR_BGR2GRAY\n",
    "\n",
    "            )\n",
    "\n",
    "            processed = cv2.Canny(\n",
    "\n",
    "                gray,\n",
    "\n",
    "                canny_low_slider.value,\n",
    "\n",
    "                canny_high_slider.value\n",
    "\n",
    "            )\n",
    "\n",
    "        else:\n",
    "\n",
    "            processed = frame_adj.copy()\n",
    "\n",
    "        ###################################################\n",
    "        # Convert to uint8\n",
    "        ###################################################\n",
    "\n",
    "        processed = np.clip(\n",
    "\n",
    "            processed,\n",
    "\n",
    "            0,\n",
    "\n",
    "            255\n",
    "\n",
    "        )\n",
    "\n",
    "        processed = processed.astype(\n",
    "\n",
    "            np.uint8\n",
    "\n",
    "        )\n",
    "\n",
    "        ###################################################\n",
    "        # Save latest frame\n",
    "        ###################################################\n",
    "\n",
    "        latest_frame = processed.copy()\n",
    "\n",
    "        ###################################################\n",
    "        # Optional Grayscale\n",
    "        ###################################################\n",
    "\n",
    "        if grayscale_checkbox.value:\n",
    "\n",
    "            if len(processed.shape) == 3:\n",
    "\n",
    "                processed = cv2.cvtColor(\n",
    "\n",
    "                    processed,\n",
    "\n",
    "                    cv2.COLOR_BGR2GRAY\n",
    "\n",
    "                )\n",
    "\n",
    "        ###################################################\n",
    "        # Prepare display images\n",
    "        ###################################################\n",
    "\n",
    "        original_color = frame_adj.copy()\n",
    "\n",
    "        if len(processed.shape) == 2:\n",
    "\n",
    "            processed_color = cv2.cvtColor(\n",
    "\n",
    "                processed,\n",
    "\n",
    "                cv2.COLOR_GRAY2BGR\n",
    "\n",
    "            )\n",
    "\n",
    "        else:\n",
    "\n",
    "            processed_color = processed.copy()\n",
    "\n",
    "        ###################################################\n",
    "        # Overlay Information\n",
    "        ###################################################\n",
    "\n",
    "        cv2.putText(\n",
    "\n",
    "            original_color,\n",
    "\n",
    "            \"Original\",\n",
    "\n",
    "            (20,40),\n",
    "\n",
    "            cv2.FONT_HERSHEY_SIMPLEX,\n",
    "\n",
    "            1,\n",
    "\n",
    "            (0,255,0),\n",
    "\n",
    "            2\n",
    "\n",
    "        )\n",
    "\n",
    "        cv2.putText(\n",
    "\n",
    "            processed_color,\n",
    "\n",
    "            mode,\n",
    "\n",
    "            (20,40),\n",
    "\n",
    "            cv2.FONT_HERSHEY_SIMPLEX,\n",
    "\n",
    "            0.8,\n",
    "\n",
    "            (0,255,0),\n",
    "\n",
    "            2\n",
    "\n",
    "        )\n",
    "\n",
    "        cv2.putText(\n",
    "\n",
    "            processed_color,\n",
    "\n",
    "            f\"FPS : {fps:.2f}\",\n",
    "\n",
    "            (20,80),\n",
    "\n",
    "            cv2.FONT_HERSHEY_SIMPLEX,\n",
    "\n",
    "            0.8,\n",
    "\n",
    "            (0,255,0),\n",
    "\n",
    "            2\n",
    "\n",
    "        )\n",
    "\n",
    "        ###################################################\n",
    "        # Combine Frames\n",
    "        ###################################################\n",
    "\n",
    "        combined = np.hstack(\n",
    "\n",
    "            (\n",
    "\n",
    "                original_color,\n",
    "\n",
    "                processed_color\n",
    "\n",
    "            )\n",
    "\n",
    "        )\n",
    "\n",
    "        ###################################################\n",
    "        # Show Window\n",
    "        ###################################################\n",
    "\n",
    "        cv2.imshow(\n",
    "\n",
    "            \"Original                     Processed\",\n",
    "\n",
    "            combined\n",
    "\n",
    "        )\n",
    "\n",
    "        ###################################################\n",
    "        # Frame Counter\n",
    "        ###################################################\n",
    "\n",
    "        frame_counter += 1\n",
    "\n",
    "        ###################################################\n",
    "        # Exit on ESC\n",
    "        ###################################################\n",
    "\n",
    "        key = cv2.waitKey(1) & 0xFF\n",
    "\n",
    "        if key == 27:\n",
    "\n",
    "            run_thread = False\n",
    "\n",
    "            break\n",
    "\n",
    "    ###################################################\n",
    "    # Cleanup\n",
    "    ###################################################\n",
    "\n",
    "    cap.release()\n",
    "\n",
    "    cv2.destroyAllWindows()\n",
    "\n",
    "    status_label.value = \"Stopped\""
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8c97a214-aa5e-4681-a2ea-f3b381760085",
   "metadata": {},
   "source": [
    "START CALLBACK FUNCTION BUTTON :"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "21a792c4-7ae0-4806-a55f-88b5372abdf8",
   "metadata": {},
   "outputs": [],
   "source": [
    "def start_video(b):\n",
    "\n",
    "    global run_thread\n",
    "    global video_thread\n",
    "    global fps_thread\n",
    "\n",
    "    if run_thread:\n",
    "        return\n",
    "\n",
    "    run_thread = True\n",
    "\n",
    "    status_label.value = \"Running\"\n",
    "\n",
    "    video_thread = threading.Thread(\n",
    "        target=process_video_stream,\n",
    "        daemon=True\n",
    "    )\n",
    "\n",
    "    fps_thread = threading.Thread(\n",
    "        target=fps_reporter,\n",
    "        daemon=True\n",
    "    )\n",
    "\n",
    "    video_thread.start()\n",
    "\n",
    "    fps_thread.start()\n",
    "\n",
    "\n",
    "start_button.on_click(start_video)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fbcbc5e6-1f62-4ea5-bfd6-2ac6c7831dfc",
   "metadata": {},
   "source": [
    "STOP CALLBACK FUNCTION BUTTON :"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "3ed407e8-faaa-4749-95ed-24be3a4ab399",
   "metadata": {},
   "outputs": [],
   "source": [
    "def stop_video(b):\n",
    "\n",
    "    global run_thread\n",
    "\n",
    "    run_thread = False\n",
    "\n",
    "    status_label.value = \"Stopped\"\n",
    "\n",
    "\n",
    "stop_button.on_click(stop_video)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "62aa4a37-5e27-4f68-8e98-849cec0b4615",
   "metadata": {},
   "source": [
    "DISPLAY GUI :"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "5f9202b0-0c60-4650-8b7e-4561499cafe3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "a3afa6aa572f4e4ebafbd8ac3fd8ffeb",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "VBox(children=(HBox(children=(Button(button_style='success', description='Start', style=ButtonStyle()), Button…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "display(\n",
    "\n",
    "widgets.VBox([\n",
    "\n",
    "widgets.HBox([\n",
    "\n",
    "start_button,\n",
    "stop_button,\n",
    "capture_button\n",
    "\n",
    "]),\n",
    "\n",
    "mode_dropdown,\n",
    "\n",
    "grayscale_checkbox,\n",
    "\n",
    "brightness_slider,\n",
    "\n",
    "contrast_slider,\n",
    "\n",
    "canny_low_slider,\n",
    "\n",
    "canny_high_slider,\n",
    "\n",
    "status_label,\n",
    "\n",
    "fps_label\n",
    "\n",
    "])\n",
    "\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4681cb1c-cfdc-4a9f-b43a-4e3f952f26b5",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fc2f2273-df4f-4e7e-ae14-39a45b4144c9",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "152c5c39-130b-4c48-9cee-6d868898275f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
